name: hello world
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # name 명령 이름
    # run 명령 
    - uses: actions/checkout@v2
    
    - name: workspace 출력
      run: echo $GITHUB_WORKSPACE

    - name: 현재 디렉터리 조회
      run: ls -al

    - name: hello world 출력
      run: echo hello world

    - name: python 버전 출력
      run: python -V

    - name: pip 업그레이드
      run: python -m pip install --upgrade pip

    - name: requirements 설치
      run: pip install -r requirements.txt

    - name: 설치된 패키지 확인
      run: pip list

    - name: python 파일 실행
      run: python './main.py'

    - name: comit
      run: |
        git config --local user.email "kuro11pow2@gmail.com"
        git config --local user.name "kuro11pow2"
        git add .
        git commit -m "데이터 추가"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
