name: crawl and push
 
on:
  # 매일 19시 32분마다 실행
  schedule:
    - cron: "32 10 * * *"
  # Actions 탭에서 수동 실행이 가능하도록 설정
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        cache: 'pip'
        python-version: '3.9'
        cache-dependency-path: './requirements.txt'
    
    - name: 정보 조회
      run: |
        echo $GITHUB_WORKSPACE
        ls -al
        python -V

    - name: 환경 설정
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 패키지 확인
      run: pip list

    - name: run script
      run: python './main.py'

    - name: commit
      run: |
        git config --local user.email "kuro11pow2@gmail.com"
        git config --local user.name "kuro11pow2"
        git add .
        git commit -m "데이터 추가"

    - name: push
      uses: ad-m/github-push-action@master
      with:
        branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}

