name: hello world
 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # name 명령 이름
    # run 명령 
    - uses: actions/checkout@v2
    - name: 파일 조회
      run: ls -al
    - name: hello world 출력
      run: echo hello world
    - name: python 버전 출력
      run: python -V
    - name: python 파일 실행
      run: python 'hello_world.py'
